// <auto-generated />
using System;
using Fishtank.Api.Data;
using Fishtank.Api.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fishtank.Api.Migrations
{
    [DbContext(typeof(FishtankDbContext))]
    [Migration("20260627000000_AddCaptureFullHeaders")]
    partial class AddCaptureFullHeaders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Fishtank.Api.Data.Entities.ServerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BootEpoch")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CaptureFullHeaders")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServerConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
